Walkover-Web-Solution/lionfapp

apps/web-giddh-admin/src/app/plans/plans-component/plans.component.ts, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
=> moment lib issue resolved

apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.html, apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.ts
staging merged with master 
latest code upadated
=> Master staging 6 feb

apps/web-giddh-admin/src/app/header/header.component.ts, apps/web-giddh-admin/src/app/theme/ng-social-login-module/auth.service.ts
=> logout issue resolved

apps/web-giddh-admin/src/app/modules/modules/api-modules/subscription.ts, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.ts
=> G0-4594: subscription get all planUniqueNames change

apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.ts, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.scss, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
User list plan name filter applied and subscribe on filter and clear filter issue resolved
=> user list plan filter applied and subscribe on filter issue fixed

apps/web-giddh-admin/src/app/header/header.component.ts, apps/web-giddh-admin/src/app/licence-key/components/generate-key/generate-key.component.ts, apps/web-giddh-admin/src/app/plans/plans-component/plans.component.html, apps/web-giddh-admin/src/app/plans/plans-component/plans.component.ts, apps/web-giddh-admin/src/app/services/catchManager/catchmanger.ts, apps/web-giddh-admin/src/app/services/general.service.ts, apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.ts, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.html, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.ts, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
Country fIlter issues resolved in Plan module.
Default sorting removed from each module.
=> bugs resolved about filter

apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts, apps/web-giddh-admin/src/app/subscription/subscription.module.ts, apps/web-giddh-admin/src/assets/css/style-2.css, package.json
=> Master to Stage

apps/web-giddh-admin/src/app/services/apiurls/subscription.api.ts, apps/web-giddh-admin/src/app/services/user.service.ts, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
UI -Integrate the api to assign the owner/ manager of the lead
=> G0-5141 | UI -Integrate the api to assign the owner/ manager of the lead

apps/web-giddh-admin/src/app/services/apiurls/subscription.api.ts, apps/web-giddh-admin/src/app/services/subscription.service.ts, apps/web-giddh-admin/src/app/subscription/components/assign-plan/assign-plan.component.html, apps/web-giddh-admin/src/app/subscription/components/assign-plan/assign-plan.component.ts, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.html, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.ts, apps/web-giddh-admin/src/app/subscription/subscription.module.ts
G0-5131 | UI - Integrate assign plan api
=> G0-5131 | UI - Integrate assign plan api 

apps/web-giddh-admin/src/app/modules/modules/api-modules/subscription.ts, apps/web-giddh-admin/src/app/subscription/components/advance-search/advance-search.component.html, apps/web-giddh-admin/src/app/subscription/components/advance-search/advance-search.component.ts, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.html, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.ts, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/theme/ng-virtual-select/sh-select.component.css
Integrated advanced search in subscription
=> Integrated advanced search in subscription

apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
=> Filtered users by owner

apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
=> Master to Staging

apps/web-giddh-admin/src/app/modules/modules/api-modules/subscription.ts, apps/web-giddh-admin/src/app/services/subscription.service.ts, apps/web-giddh-admin/src/app/subscription/components/advance-search/advance-search.component.html, apps/web-giddh-admin/src/app/subscription/components/advance-search/advance-search.component.ts, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.ts, apps/web-giddh-admin/src/assets/css/style-2.css
Fixed G0-5225 | Prod - All filters for Remaining transactions field in Advance Search in Subscriptions module in Admin Panel is not working correctly
=> Fixed G0-5225 | Prod - All filters for Remaining transactions field in Advance Search in Subscriptions module in Admin Panel is not working correctly

apps/web-giddh-admin/src/app/subscription/components/advance-search/advance-search.component.html
Fixed G0-5227 | Vtest - In Admin Panel On Advance Search page in Subscription module the date picker is overlapping the field for which it is opened
=> Fixed G0-5227 | Vtest - In Admin Panel On Advance Search page in Subscription module the date picker is overlapping the field for which it is opened 

apps/web-giddh-admin/src/app/subscription/components/advance-search/advance-search.component.html
Vtest - In Admin Panel On Advance Search page in Subscription module the date picker is overlapping the field for which it is opened
=> Vtest - In Admin Panel On Advance Search page in Subscription module the date picker is overlapping the field for which it is opened 

apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts, package.json
Upgraded Datepicker Module and added inline datepicker
=> Upgraded Datepicker Module and added inline datepicker

apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
Displayed single datepicker for date range
=> Displayed single datepicker for date range

apps/web-giddh-admin/src/app/subscription/components/advance-search/advance-search.component.html, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.ts
G0-5247 | Vtest - Value is retained in name of filter field for "Remaining Transactions" in Advance Search after filter is cleared
=> G0-5247 | Vtest - Value is retained in name of filter field for "Remaining Transactions" in Advance Search after filter is cleared

apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html
Fixed G0-5269 | Vtest- Clear filter is not displayed for "Is Unknown" and "Has Any Value" filters on "Last Seen" page
=> Fixed G0-5269 | Vtest- Clear filter is not displayed for "Is Unknown" and "Has Any Value" filters on "Last Seen" page 

apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html
Fixed G0-5268 | Vtest - Extra space between On, Between and Is Unknown radio buttons on "Last Seen" page
=> Fixed G0-5268 | Vtest - Extra space between On, Between and Is Unknown radio buttons on "Last Seen" page 

apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
Fixed - G0-5267 | Vtest - Search results for filters "After", "Before", "On" and "Has Any Value" are not correct
=> Fixed - G0-5267 | Vtest - Search results for filters "After", "Before", "On" and "Has Any Value" are not correct

apps/web-giddh-admin/src/app/subscription/components/advance-search/advance-search.component.html, apps/web-giddh-admin/src/app/subscription/components/assign-plan/assign-plan.component.html
card no.  https://giddha.atlassian.net/browse/G0-5403
Vtest - In Advance search on the subscription page for field "Subscribed on" , "O" should be capital and in Assign Plan screen field name should be Plan instead of "Plans""
=> content changes  In Advance search on the subscription page

apps/web-giddh-admin/src/app/services/subscription.service.ts, apps/web-giddh-admin/src/app/subscription/components/suscription-container/subscription-container.component.ts, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
=> Fixed Staging PR issues

apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.ts, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.ts
=> fixed issues

apps/web-giddh-admin/src/app/plans/plans-component/plans.component.html, apps/web-giddh-admin/src/app/plans/plans-component/plans.component.scss, apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.html, apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.scss, apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.ts, apps/web-giddh-admin/src/app/subscription/components/user-list/user-list.component.html, apps/web-giddh-admin/src/assets/css/style-2.css
1. Add permission column in the company page and view button in td when. user click on view button model should be open.
2. Clear filter the same as giddh in all pages.
3. When users apply a filter ( pop up filter) like a plan, companies, etc hence border should be in blue color.
4. add a column for the last login and last entry date in the company page.
5. dropdown width height scrolling issues
6. also worked on this card https://giddha.atlassian.net/browse/G0-7989
=> Advance search alignment

apps/web-giddh-admin/src/app/subscription/components/edit-subscriptions/edit-subscriptions.component.html, apps/web-giddh-admin/src/assets/css/style-2.css
=> sadique | admin panel back button
